apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: utopiadevkv
  namespace: utopia-sc-akv-test  # Use the namespace from your pod setup
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useManagedIdentity: "true"
    keyvaultName: "utopiadevkv"  # Matches your Terraform Key Vault name
    objects: |
      array:
        - |
          objectName: tyson-testing
          objectType: secret
    resourceGroup: "rg-sandbox-utopia-dev"  # Matches your Terraform resource group
    subscriptionId: "26b97e4e-60bf-4cbf-8d0d-d4a0f52b6dcd"  # Replace with your sandbox subscription ID
    tenantId: "105b8f4e-e6bd-43e7-9fb8-20feeb27f3b6"  # Replace with your Azure AD tenant ID